apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-pv-claim
spec:
  storageClassName: ping-pong-pv-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
