apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-random-task-cj
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: create-post-container
              image: create-post-run:latest
              imagePullPolicy: Never
              env:
                - name: URL
                  valueFrom:
                    configMapKeyRef:
                      key: POSTS_URL
                      name: todo-app-cm
          restartPolicy: OnFailure
