apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-app
  template:
    metadata:
      labels:
        app: todo-app-app
    spec:
      containers:
        - name: todo-app-app
          image: todo-app-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: todo-app-vol
              mountPath: /tmp
          env:
            - name: POSTS_URL
              value: "http://todo-backend-svc:8085/posts"
        - name: todo-backend-app
          image: todo-backend-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
      volumes:
        - name: todo-app-vol
          persistentVolumeClaim:
            claimName: todo-app-pvc
