apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-app
  template:
    metadata:
      labels:
        app: todo-app-app
    spec:
      containers:
        - name: todo-app-app
          image: todo-app-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: todo-app-vol
              mountPath: /tmp
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: todo-app-cm
        - name: todo-backend-app
          image: todo-backend-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: project-secret
                  key: DB_URL
      volumes:
        - name: todo-app-vol
          persistentVolumeClaim:
            claimName: todo-app-pvc
