apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-app-pvc
  namespace: project
spec:
  storageClassName: todo-app-pv-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
