apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: TODO_APP_APP
    newName: todo-app-app
    newTag: latest
  - name: TODO_BACKEND_APP
    newName: todo-backend-app
    newTag: latest
  - name: CREATE_POST_RUN
    newName: create-post-run
    newTag: latest
  - name: PG_BACKUP_IMAGE
    newName: pg-backup
    newTag: latest
resources:
  - ../manifests/namespace.yaml
  - ../manifests/configmap.yaml
  - ../manifests/cronjob.yaml
  - ../manifests/deployment.yaml
  - ../manifests/dec/secrets.yaml
  - ../manifests/persistent-volume-claim.yaml
  - ../manifests/persistent-volume.yaml
  - ../manifests/ingress.yaml
  - ../manifests/service.yaml
  - ../manifests/service_backend.yaml
  - ../manifests/statefulset.yaml
