apiVersion: v1
kind: Service
metadata:
  name: greeter-svc
spec:
  type: ClusterIP
  selector:
    app: greeter
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-v1
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v1
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-v2
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v2
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
