# This rule is not used by the project dummysite itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to stable.dwk.stable.dwk resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dummysite
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-viewer-role
rules:
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - dummysites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - dummysites/status
  verbs:
  - get
