# This rule is not used by the project dummysite itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the stable.dwk.stable.dwk.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dummysite
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-editor-role
rules:
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - dummysites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stable.dwk.stable.dwk
  resources:
  - dummysites/status
  verbs:
  - get
