apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 8080
