apiVersion: v1
kind: Secret
metadata:
    name: project-secret
    namespace: project
stringData:
    DB_URL: ENC[AES256_GCM,data:nRWiny7fog1PoSv9LqSgidxD2h/Zz/1fYwE8dLHOnuriFcmhlXRRs/GNBRADu7BtqrahqIuVIbu/sM//sxHkwugjyps9NIpgS6aGVKhO4oQ=,iv:trZkT8nLRjS0TjzLrggjKxjCU+/2PoAqgxH5W8ed1Hg=,tag:8qz0sLVDpgfcXpqROfiivg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:HpJHubjoFzQ=,iv:yV8507Dv3Fy19GQtHWzy/okVzVwpWbGnG6F28FR6Ejw=,tag:qv9P6nn7y73a6raFZCsRrA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:roQvTwffb/iHt4QP,iv:GGZn6kHu0No9ih76bND3zLa5cHi4kdsnfbAxXN6RJk0=,tag:Wb/NSsOD97vlQ00WeYB6EA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:KF+xR3CI,iv:LCNjgXhJEOqUxHN0BBhsj7PSjpafliz4ZjnlNfhI5BQ=,tag:iAswiZ7tKGDYw/ScC0SOWA==,type:str]
sops:
    age:
        - recipient: age1ekqjgmayst3ugq4fv405gts384l7jd4d4fqnpazxwg5v0vauwfjqa2x7pc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTllOdnNnVi96eFN1ZkRR
            MFAvc2gxUEk2YTUrcWdPcytZSXBQR3dCMmw4Cjl5SjI5bnRWVVVieFBTdUplMmdh
            Qm52RllXdDZUaFprcFFLMStqbVl0Z0kKLS0tIFFPcm9ycUtMSE82emhNNDJjbFkr
            Yy9ZRTZSaWZhUnRWcWsxR0VGc0UvVmcKLTV0vVb94z1VIpSx2yhcqn8UZ/I77A+y
            Q+Y6hRQhuhcXmUOkQSiRiUCG6JtKqB3xYJ1TguzhVHDjtCFSizgrww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T16:32:27Z"
    mac: ENC[AES256_GCM,data:CSaH/yhYU+7RHrgmB1xyXmlc/b1a18/0PzZ8O7JjMQetoz1cCtoXORWHEIDXEu91khb9/eAiG1n/vqt/49DsUeftbZO4bRXjSo6d9hk+HyZwYQnS8cChLRgY9WqZuIPkC1tLUGqNyqLT5jClKoPgvgn3pKZDbBvPmLnOvSBgI0U=,iv:qsJwWCvVoByqvgvJaOFSnRgzdFfwQ8JrMKzM/YOvWM0=,tag:08tVc3rQaSNBcYn1FgTefg==,type:str]
    encrypted_regex: (Data)$
    version: 3.11.0
