apiVersion: v1
kind: Secret
metadata:
  name: project-secret
  namespace: project
stringData:
  DB_URL: ENC[AES256_GCM,data:OsU+r72u5iDDmNuymMex08mO+8PJOu1BrX0xJnaE1JA/NGIqP188ne2jmpLR/h5+x7ynbDyBcUkEjb7xXSv/tcpEXPrV7xMYJokBFlmkij0=,iv:fBPAN7dB+vkSkkuZXwEfa6fq5SxLFWKp+sBATuP875M=,tag:Cw/gzwBu0S0cOwovcYexuQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:RkI7vByT22M=,iv:LarvjoWqpwcXytNVYX3SEiQyysi6h33ZkBOEl6aA/h8=,tag:LTqnSQ0fzxs+ly4LhoU9sw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:xWSfB7ifShxJVi7g,iv:V7IMZ+Cyi9pgYatHip1JbEyMycLSNvI5+7EYS/yQDLQ=,tag:rX+DQcm8tOF4D+9v2CaGJQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:43Ta7dsX,iv:wpY1bFVnKVS+WDywfhel+vnal66I4BUSaun2ZeudeBs=,tag:M52HlEBmZqHPqPV+oOc7lQ==,type:str]
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:DVetlc0Hb+9A361PyzeXW8e2v/mDQxs/xVH2pUtL7yARC8rre31cWAR9Q/gvzw==,iv:UBe87/1OOGK/r4XCR3cz09SdOTyV9ePaj6Bw64NfrhU=,tag:1nNEsLGFnUZQU9n4sTU+6A==,type:str]
  TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:dhvbaM6EUrRVyQ==,iv:xjsfvI4pS9mLNh0vEeltmmc/WS4VXrK/MxID79U0d80=,tag:7Vul5q1NINIHxCWUozJTXA==,type:str]
sops:
  age:
    - recipient: age1ekqjgmayst3ugq4fv405gts384l7jd4d4fqnpazxwg5v0vauwfjqa2x7pc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa1lPa3N3RkJudjFZU3ZO
        aWdKbEhWWVdnK3Y5U3prS3ovMHlOUVFDdDBRCjJ3dDAvdTBUcmw0TXVBYjVLQWRN
        OGZGYkF3KzBWUis5VUc0REl4Q3M3UUkKLS0tIFU0UktVeWx2eE5YbE1DRzhZL3Rx
        cmE4QXNHK0g0RG9UTUxyWThicytmdFEKGtxU4MjM3NxHjwYfmOinBLdNMY0qybCJ
        MtI2RZwQ94x4gFQTI5I19RvEfTVmRjfvFGm8+YvzbtA8JH8+O0+5gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T15:09:39Z"
  mac: ENC[AES256_GCM,data:9Z+DiSa4Yn8plNTZxsP9r1/us3KNUKRSJcf6yTVlfjs7HC1y18DHCOkNoBU/szSTuLnAwtkbG99BIhxZaPddhAsILsmJOJPMzbNoF+fG/uf+LtenxTc+1v/mR+qw1ngh6n593rDqf/0klXvZaYvSjlcJljHy5ePV77GpjBrjmf0=,iv:SHDANR4Y4v3Z89MQ8AITu/0wK7jt7Qflf6fFpG7yKg8=,tag:1hvLjrCOE7umkioAeWvJxw==,type:str]
  encrypted_regex: (stringData)
  version: 3.11.0
