apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PING_PONG_APP
  newName: kirillstrelkov/ping-pong-app
  newTag: e5b0793d6966abcd9a2e60fe4abdfd5e7fb66c7c
resources:
- ../manifests/namespace.yaml
- ../manifests/enc/deployment.yaml
- ../manifests/enc/statefulset.yaml
- ../manifests/analysistemplate.yaml
- ../manifests/ingress.yaml
- ../manifests/service.yaml
