apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: TODO_APP_APP
    newName: europe-north1-docker.pkg.dev/dwk-gke-479211/my-docker-repo/todo-app-app
    newTag: v1
  - name: TODO_BACKEND_APP
    newName: europe-north1-docker.pkg.dev/dwk-gke-479211/my-docker-repo/todo-backend-app
    newTag: v1
  - name: CREATE_POST_RUN
    newName: europe-north1-docker.pkg.dev/dwk-gke-479211/my-docker-repo/create-post-run
    newTag: v1
  - name: PG_BACKUP_IMAGE
    newName: europe-north1-docker.pkg.dev/dwk-gke-479211/my-docker-repo/pg-backup
    newTag: v2
resources:
  - manifests/configmap.yaml
  - manifests/cronjob.yaml
  - manifests/deployment.yaml
  - manifests/dec/secrets.yaml
  - manifests/gke/gateway.yaml
  - manifests/gke/health-check.yaml
  - manifests/gke/backup-cronjob.yaml
  - manifests/persistent-volume-claim.yaml
  - manifests/service.yaml
  - manifests/service_backend.yaml
  - manifests/statefulset.yaml
  - manifests/storageclass.yaml
