apiVersion: stable.dwk.stable.dwk/v1
kind: DummySite
metadata:
  labels:
    app.kubernetes.io/name: dummysite
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-k8s-wiki
  namespace: exercises
spec:
  website_url: "https://en.wikipedia.org/wiki/Kubernetes"
