apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PING_PONG_APP
    newName: kirillstrelkov/ping-pong-app
    newTag: v3
resources:
  - manifests/namespace.yaml
  - manifests/dec/deployment.yaml
  - manifests/dec/statefulset.yaml
  - manifests/analysistemplate.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
