apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: log-pp-gateway
  namespace: exercises
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: log-pp-route
  namespace: exercises
spec:
  parentRefs:
    - name: log-pp-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /pings
      backendRefs:
        - name: ping-pong-svc
          port: 3456
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ping-pong-svc
          port: 3456
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: log-output-svc
          port: 2345
