apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-output-app
          image: log-output-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PING_PONG_SERVICE
              value: ping-pong-svc:3456
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-cm
                  key: MESSAGE
          volumeMounts:
            - name: config-vol
              mountPath: /tmp
      volumes:
        - name: config-vol
          configMap:
            name: log-output-cm
