apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-output-app
          image: LOG_OUTPUT_APP
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PING_PONG_SERVICE
              value: ping-pong-svc:3456
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-cm
                  key: MESSAGE
            - name: GREETER_SERVICE
              value: greeter-svc:80
          volumeMounts:
            - name: config-vol
              mountPath: /tmp
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
      volumes:
        - name: config-vol
          configMap:
            name: log-output-cm
