apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: shared-tmp
          persistentVolumeClaim:
            claimName: ping-pong-pv-claim
      containers:
        - name: log-output-writer-app
          image: log-output-writer-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-tmp
              mountPath: /tmp

        - name: log-output-reader-app
          image: log-output-reader-app:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-tmp
              mountPath: /tmp
