apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - name: log-output-writer-app
          image: log-output-writer-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts: # Mount volume
            - name: shared-image
              mountPath: /tmp

        - name: log-output-reader-app
          image: log-output-reader-app:latest
          imagePullPolicy: Never
          volumeMounts: # Mount volume
            - name: shared-image
              mountPath: /tmp
