apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: log-gateway-istio
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: routing-paths
spec:
  parentRefs:
    - name: log-gateway-istio
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: log-output-svc
          port: 2345
    - matches:
        - path:
            type: PathPrefix
            value: /pings
      backendRefs:
        - name: ping-pong-svc
          port: 3456

    - matches:
        - path:
            type: PathPrefix
            value: /stress
      backendRefs:
        - name: ping-pong-svc
          port: 3456

    - matches:
        - path:
            type: PathPrefix
            value: /ping
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ping-pong-svc
          port: 3456
