apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-app
  template:
    metadata:
      labels:
        app: todo-app-app
    spec:
      containers:
        - name: todo-app-app
          image: todo-app-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: todo-app-vol
              mountPath: /tmp
      volumes:
        - name: todo-app-vol
          persistentVolumeClaim:
            claimName: todo-app-pvc
