apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: LOG_OUTPUT_APP
  newName: kirillstrelkov/log-output
  newTag: 01c23871794f4e374742b1a7cad6d9595026daa0
resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/service.yaml
