apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: LOG_OUTPUT_APP
    newName: log-output-app
    newTag: v4
namespace: exercises
resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
  - manifests/greeter/deployment.yaml
  - manifests/greeter/service.yaml
  - manifests/greeter/route.yaml
  - manifests/istio-gateway.yaml
