apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: LOG_OUTPUT_APP
    newName: kirillstrelkov/log-output-app
    newTag: v1
resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
