apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manifests/configmap.yaml
  - ../../manifests/cronjob.yaml
  - ../../manifests/deployment.yaml
  - ../../manifests/broadcaster-dep.yaml
  - ../../manifests/service.yaml
  - ../../manifests/service_backend.yaml
  - ../../manifests/statefulset.yaml
